// Code generated by "stringer -type CommandUnstable"; DO NOT EDIT.

package proto

import "strconv"

const _CommandUnstable_name = "CmdDrawImageCmdUpdateScreenCmdPlaySoundCmdButtonPressedActionCmdButtonReleasedAction"

var _CommandUnstable_index = [...]uint8{0, 12, 27, 39, 61, 84}

func (i CommandUnstable) String() string {
	i -= 1
	if i >= CommandUnstable(len(_CommandUnstable_index)-1) {
		return "CommandUnstable(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CommandUnstable_name[_CommandUnstable_index[i]:_CommandUnstable_index[i+1]]
}
