// Code generated by "stringer -type CommandStable"; DO NOT EDIT.

package proto

import "strconv"

const _CommandStable_name = "CmdLoadFile"

var _CommandStable_index = [...]uint8{0, 11}

func (i CommandStable) String() string {
	i -= 1
	if i >= CommandStable(len(_CommandStable_index)-1) {
		return "CommandStable(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CommandStable_name[_CommandStable_index[i]:_CommandStable_index[i+1]]
}
