// Code generated by "stringer -linecomment -type PlayerClass"; DO NOT EDIT.

package main

import "strconv"

const _PlayerClass_name = "WarriorRogueSorceror"

var _PlayerClass_index = [...]uint8{0, 7, 12, 20}

func (i PlayerClass) String() string {
	if i >= PlayerClass(len(_PlayerClass_index)-1) {
		return "PlayerClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlayerClass_name[_PlayerClass_index[i]:_PlayerClass_index[i+1]]
}
