// Code generated by "stringer -type Class"; DO NOT EDIT.

package player

import "strconv"

const _Class_name = "WarriorRogueSorceror"

var _Class_index = [...]uint8{0, 7, 12, 20}

func (i Class) String() string {
	if i >= Class(len(_Class_index)-1) {
		return "Class(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Class_name[_Class_index[i]:_Class_index[i+1]]
}
