package l1

// TileID specifies the graphics of a tile.
type TileID uint8

// Tile IDs.
const (
	WallSw TileID = iota + 1
	WallSe
	ArchNeArchNw
	WallSwWallSe
	ArchSwArchSe
	WallEndSw
	WallEndSe
	ArchEndSw
	ArchEndSe
	WallSwArchSe
	ArchSw
	ArchSe
	Floor
	ArchSwWallSe
	Column
	ArchEndNe
	ArchEndNw
	DirtWallSw
	DirtWallSe
	DirtWallNeWallNw
	DirtWallSwWallSe
	Dirt
	DirtWallEndSw
	DirtWallEndSe
	DoorSw
	DoorSe
	WallSwBarSe
	DoorSwDoorSe
	BarSwBarSe
	DoorEndSw
	DoorEndSe
	BarEndSw
	BarEndSe
	DoorSwBarSe
	BarSw
	BarSe
	BarSwWallSe
	BarSwArchSe
	BarSwDoorSe
	DoorSwArchSe
	DoorSwWallSe
	ArchSwDoorSe
	WallSwDoorSe
	ArchSwBarSe
	CircleMarking1
	CircleMarking2
	CircleMarking3
	CircleMarking4
	CircleMarking5
	CircleMarking6
	CircleMarking7
	CircleMarking8
	CircleMarking9
	CircleMarking10
	CircleMarking11
	CircleMarking12
	StairA1
	StairA2
	StairA3
	StairA4
	StairA5
	StairA6
	StairB1
	StairB2
	StairB3
	StairB4
	StairB5
	StairB6
	Tomb1
	Tomb2
	Tomb3
	Tomb4
	Tomb5
	Tomb6
	Tomb7
	Tomb8
	Tomb9
	Tomb10
	WallSw2
	WallSe2
	WallNeWallNw
	WallSwWallSe2
	WallSw3
	WallEndSw2
	WallEndSe2
	WallEndNe
	WallEndNw
	WallSe3
	TapestryWallSw1
	TapestryWallSw2
	TapestryWallSe1
	TapestryWallSe2
	WallSw4
	TombWallSw
	TombWallSe
	WallSe4
	BloodWallSe1
	BloodWallSe2
	BloodWallSe3
	BloodWallSw1
	BloodWallSw2
	BloodArchSw
	BloodDoorSw
	BloodFloor1
	BloodFloor2
	BloodFloor3
	CrossWallSw
	CrossWallSe
	NicheWallSw
	NicheWallSe
	StatueWallSw
	StatueWallSe
	TorchWallSw
	TorchWallSe
	BrokenWallSe1
	BrokenWallSe2
	BrokenWallSe3
	BrokenArchSe
	BrokenEnteranceSe1
	BrokenEnteranceSe2
	BrokenArchSw1
	BrokenWallSw1
	BrokenArchSw2
	BrokenWallSw2
	BrokenFloor1
	BrokenEnteranceSw1
	BrokenEnteranceSw2
	Candlestick1
	Candlestick2
	Candlestick3
	Sarcophagus1
	Sarcophagus2
	BrokenFloor2
	BrokenFloor3
	BrokenFloor4
	BrokenFloor5
	BrokenFloor6
	BrokenFloor7
	FloorShadowArchSwRight
	FloorShadowArchSeLeft
	FloorShadowBarSwRight
	FloorShadowShaftRight
	FloorShadowArchSeLeftShaftBottom
	FloorShadowShaftBottom1
	FloorShadowColumnBottom
	WallSwShadowArchSeLeft
	ArchSwShadowArchSeLeft
	WallSeShadowArchSwRight
	ArchSeShadowArchSwRight
	FloorShadowArchSeLeftArchSwRight
	FloorShadowShaftBottomArchSwRight
	FloorShadowShaftBottom2
	ArchSeShadowBarSwRight
	WallSeShadowBarSwRight
	WallSw3ShadowArchSeLeft
	WallSe3ShadowArchSwRight
	WallSe3ShadowBarSwRight
	WallSwWallSe3
	ArchSwWallSe3
	WallSw3WallSe
	WallSw3ArchSe
	Floor2
	Floor3
	DoorSwWallSe3
	WallSw3DoorSe
	BloodWallSw3
	BloodWallSw4
	BloodWallSwWallSe
	BloodWallSe4
	BloodWallSe5
	BloodFloor4
	BloodFloor5
	BloodFloor6
	BloodFloor7
	OpenDoorSw
	OpenDoorSe
	OpenDoorSwOpenDoorSe
	OpenDoorEndSw
	OpenDoorEndSe
	OpenDoorSwBarSe
	BarSwOpenDoorSe
	OpenDoorSwArchSe
	OpenDoorSwWallSe
	ArchSwOpenDoorSe
	WallSwOpenDoorSe
	OpenBloodDoorSw
	OpenDoorSwWallSe3
	WallSw3OpenDoorSe
	OpenDoorSwDoorSe
	DoorSwOpenDoorSe
	WallSw5
	WallSe5
	EnteranceSw1
	EnteranceSe1
	DirtFloorShadow
	DirtFloorShadowArchSwRight
	EnteranceSw2
	EnteranceSe2
	DirtWallSwDirt
	DirtWallSeDirt
	DirtWallNeWallNwDirt
	DirtWallSwWallSeDirt
	DirtDirt
	DirtWallEndSwDirt
	DirtWallEndSeDirt
	BrokenEnteranceSe3
)
